nohup: ignoring input
*********  Fitting light curves   ******************
0 modelnum = 70 sntype= AGN
Current procedures:  ['lcfit']
Load base fit input file.. /media/emille/git/COIN/RESSPECT_repo/RESSPECT//auxiliary_files/baseinputs/perfect_sim_v1.nml
Setting key VERSION_PHOTOMETRY=LSST_WFD_MODEL70 in &SNLCINP
Addding key SNCID_LIST_FILE=results/WFD/salt3_AGN/snid/AGN_WFD_photoids_plasticc_1.dat_test_70 in &SNLCINP
Setting key PRIVATE_DATA_PATH=/media/RESSPECT/data/PLAsTiCC/SNANA/ in &SNLCINP
Setting key TEXTFILE_PREFIX=results/WFD/salt3_AGN/test_fitres_1_0 in &SNLCINP
Write fit input to file: results/WFD/salt3_AGN/pipelineinputs/snfit_TEST.nml.temp.1631751219.8395662
Running snlc_fit.exe /media/emille/git/COIN/RESSPECT_work/PLAsTiCC/metrics_paper/resspect_metric/clean_code/results/WFD/salt3_AGN/pipelineinputs/snfit_TEST.nml.temp.1631751219.8395662
Traceback (most recent call last):
  File "01_SALT2_fit.py", line 184, in <module>
    outputdir='results/' + subsample + '/salt3_' + sntype)
  File "/media/emille/git/COIN/RESSPECT_repo/RESSPECT/resspect/salt3_utils.py", line 142, in get_distances
    hook.run() 
  File "/media/emille/git/COIN/RESSPECT_repo/RESSPECT/resspect/snanapipe/snana_hook.py", line 20, in run
    self.pipe.run()
  File "/media/RESSPECT/SALT3/salt3/pipeline/pipeline.py", line 218, in run
    pipepro.run(batch=pipepro.batch)
  File "/media/RESSPECT/SALT3/salt3/pipeline/pipeline.py", line 479, in run
    else: self.success = _run_external_pro(self.pro, args)
  File "/media/RESSPECT/SALT3/salt3/pipeline/pipeline.py", line 1244, in _run_external_pro
    raise ValueError("Something went wrong..") ##possible to pass the error msg from the program?
ValueError: Something went wrong..
